source 'http://rubygems.org'
gem 'cucumber', '3.0.1'
gem 'ffi', '1.3.1'
gem 'capybara', '~> 2.7'
gem 'selenium-webdriver', '2.45.0'
gem 'curb', '0.9.4'
gem 'titleize', '1.2.1'
gem 'json', '1.7.7'
gem 'syntax'
gem 'minitest'
gem 'pry', '0.11.1'
gem 'rspec-expectations'
